name: Test Coverage workflow

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' 
    - name: Install gems
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundler install
    - name: Run rspec
      run: rspec
