name: Test Coverage workflow

on: [pull_request]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' 
        bundler-cache: true
    - name: Install gems
      run: |
        sudo apt-get -yqq install libpq-dev tree links
        gem install bundler
        bundler install
    - name: Run test
      run: rspec
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.number }}-coverage_report-${{ steps.current-time.outputs.time }}
        path: /home/runner/work/rspec-coverage/rspec-coverage/coverage/index.html
        retention-days: 1
    - name: Simplecov Report
      uses: lendkhoa/simplecov-report-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        failedThreshold: 18